server:
  port: 9003

spring:
  application:
    name: spring-api-gateway
  config:
    import: configserver:http://localhost:9004
  cloud:
    gateway:
      mvc:
        routes:
          - id: spring-core-service
            uri: lb://spring-core-service
            predicates:
              - Path=/core/**
          - id: spring-middle-service
            uri: lb://spring-middle-service
            predicates:
              - Path=/middle/**
