server:
  port: 9000

spring:
  application:
    name: spring-registry-server
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com:
      netflix:
        discovery: OFF
        eureka: OFF
