server:
  port: 9004

spring:
  application:
    name: spring-config-server

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:9000/eureka}

logging:
  level:
    com:
      netflix:
        discovery: OFF
        eureka: OFF