server:
  port: 9004

spring:
  application:
    name: spring-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jwoliv/spring-microservices-config
          clone-on-start: true
